AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys all components to support the bastion, with the
  exception of those related to BIG-IP. An autoscaling group for the
  bastion is created.
Conditions:
  useBastionSecurityGroupId: !Not
    - !Equals
      - !Ref bastionSecurityGroupId
      - ''
  useStaticIp: !Not
    - !Equals
      - !Ref staticIp
      - ''
  useCustomImage: !Not
    - !Equals
      - !Ref customImageId
      - ''
  Standalone: !Equals
    - 'false'
    - !Ref createAutoscaleGroup
  Autoscale: !Equals
      - 'true'
      - !Ref createAutoscaleGroup
Mappings:
  imageRegionMap:
    us-east-2:
      AMI: ami-0ab8744dca8137bde
    us-east-1:
      AMI: ami-00543d76373f96fe7
    us-gov-east-1:
      AMI: ami-08db47abb3873cf32
    us-gov-west-1:
      AMI: ami-023d2b48de48d500d
    us-west-1:
      AMI: ami-04bdbbe85ee49bfa4
    us-west-2:
      AMI: ami-0f2058e5300317758
    af-south-1:
      AMI: ami-08098e0f3576e4a5b
    ap-east-1:
      AMI: ami-053c7215ee0315735
    ap-south-1:
      AMI: ami-0c90942fd0daf9bc5
    ap-northeast-1:
      AMI: ami-0448a132eb2ded7b8
    ap-northeast-2:
      AMI: ami-006b0b933762bbcef
    ap-southeast-1:
      AMI: ami-084952bed7e34d3de
    ap-southeast-2:
      AMI: ami-071e2a45ff7eda67a
    ca-central-1:
      AMI: ami-059972b88fabb1811
    eu-central-1:
      AMI: ami-0022e2e80fa74c5d7
    eu-west-1:
      AMI: ami-05145bc4cc62a2a9a
    eu-west-2:
      AMI: ami-0ad9754b60e77a766
    eu-west-3:
      AMI: ami-03756f8c316f89afb
    eu-south-1:
      AMI: ami-050515e83b5887c23
    eu-north-1:
      AMI: ami-0356765f5ba4892f5
    il-central-1:
      AMI: ami-0b72974188c516a3f
    me-south-1:
      AMI: ami-09f2ee1ca942a02ca
    sa-east-1:
      AMI: ami-006c2c053c07213b2
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Application Settings
        Parameters:
          - bastionSecurityGroupId
          - mgmtSubnet
          - mgmtSubnets
          - createAutoscaleGroup
          - customImageId
          - instanceType
          - restrictedSrcAddress
          - scalingMaxSize
          - scalingMinSize
          - sshKey
          - staticIp
          - vpc
      - Label:
          default: Resources Tags
        Parameters:
          - uniqueString
          - application
          - cost
          - environment
          - group
          - owner
    ParameterLabels:
      application:
        default: Application
      cost:
        default: Cost Center
      environment:
        default: Environment
      group:
        default: Group
      owner:
        default: Owner
      bastionSecurityGroupId:
        default: The resource ID of a security group to apply to the mgmt
      mgmtSubnet:
        default: Management Subnet ID used in case of standalone mgmt
      mgmtSubnets:
        default: Management Subnet IDs
      createAutoscaleGroup:
        default: The ARN of the AWS secret containing the password used during BIG-IP licensing via BIG-IQ
      instanceType:
        default: Must be a valid EC2 instance type for BIG-IP
      restrictedSrcAddress:
        default: The IP address range used to SSH and access management GUI on the EC2 instances
      scalingMaxSize:
        default: Maximum number of BIG-IP instances (2-100) that can be created in the Auto Scale Group
      scalingMinSize:
        default: Minimum number of BIG-IP instances (1-99) you want available in the Auto Scale Group
      sshKey:
        default: Supply the public key that will be used for SSH authentication to the BIG-IP and Bastion virtual machines
      staticIp:
        default: The private IP address to apply as primary private address
      uniqueString:
        default: Unique string
      vpc:
        default: VPC ID
  Version: 3.6.0.0
Outputs:
  stackName:
    Description: bastion nested stack name
    Value: !Ref "AWS::StackName"
  bastionAutoscaleGroupName:
    Condition: Autoscale
    Value: !Ref bastionAutoscaleGroup
  bastionInstanceId:
    Condition: Standalone
    Description: Bastion server instance-id
    Value: !Ref BastionInstance
  bastionPublicIp:
    Condition: Standalone
    Description: bastion's public IP address
    Value: !GetAtt BastionInstance.PublicIp
Parameters:
  bastionSecurityGroupId:
    Default: ''
    Description: The resource ID of a security group to apply to the Bastion.
    Type: String
  application:
    Default: f5app
    Description: Application Tag.
    MaxLength: 50
    Type: String
  mgmtSubnet:
    Default: ''
    Description: Management Subnet ID used in case of standalone Bastion host.
    Type: String
  mgmtSubnets:
    Default: ''
    Description: Management Subnet IDs.
    Type: CommaDelimitedList
  cost:
    Default: f5cost
    Description: Cost Center Tag.
    Type: String
  createAutoscaleGroup:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Choose true to create the Bastion instances in an autoscaling configuration.
    Type: String
  customImageId:
    Default: ''
    Description: Provide Custom Image AMI ID you wish to deploy.
    Type: String
  environment:
    Default: f5env
    MaxLength: 50
    Type: String
  group:
    Default: f5group
    MaxLength: 50
    Type: String
  instanceType:
    ConstraintDescription: Must be a valid EC2 instance type for BIG-IP
    Default: t3.small
    Description: Enter valid instance type.
    Type: String
  owner:
    Default: f5owner
    MaxLength: 50
    Type: String
  restrictedSrcAddress:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Description: REQUIRED - The IP address range used to SSH and access management GUI on the EC2 instances.
    MaxLength: '18'
    MinLength: '9'
    Type: String
  scalingMaxSize:
    ConstraintDescription: Must be a number between 2-100
    Default: 2
    Description: Maximum number of BIG-IP instances (2-100) that can be created in the Auto Scale Group.
    MaxValue: 100
    MinValue: 2
    Type: Number
  scalingMinSize:
    ConstraintDescription: Must be a number between 1-99
    Default: 1
    Description: Minimum number of BIG-IP instances (1-99) you want available in the Auto Scale Group.
    MaxValue: 99
    MinValue: 1
    Type: Number
  sshKey:
    Description: REQUIRED - Supply the public key that will be used for SSH authentication to the bastion virtual machines.
    Type: AWS::EC2::KeyPair::KeyName
  staticIp:
    Default: ''
    Description: The private IP address to apply as primary private address. The address must reside in the subnet provided in the subnetId parameter. ***NOTE:*** When set to empty string, DHCP will be used for allocating ip address.
    Type: String
  uniqueString:
    AllowedPattern: ^[a-z][a-z0-9]{1,11}$
    ConstraintDescription: Must contain between 1 and 12 lowercase alphanumeric characters with first character as a letter.
    Default: myuniqstr
    Description: Unique String used when creating object names or Tags.
    Type: String
  vpc:
    Description: REQUIRED - VPC ID.
    Type: AWS::EC2::VPC::Id
Resources:
  BastionInstance:
    Condition: Standalone
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId:
        !If
        - useCustomImage
        - !Ref customImageId
        - !FindInMap
          - imageRegionMap
          - !Ref 'AWS::Region'
          - AMI
      InstanceType: !Ref instanceType
      KeyName: !Ref sshKey
      NetworkInterfaces:
        !If
        - useStaticIp
        -
          - AssociatePublicIpAddress: true
            DeviceIndex: "0"
            SubnetId: !Ref mgmtSubnet
            GroupSet:
              - !If
                - useBastionSecurityGroupId
                -
                  !Ref bastionSecurityGroupId
                - !Ref AWS::NoValue
            PrivateIpAddress: !Ref staticIp
        -
          - AssociatePublicIpAddress: true
            DeviceIndex: "0"
            SubnetId: !Ref mgmtSubnet
            GroupSet:
              - !If
                - useBastionSecurityGroupId
                -
                  !Ref bastionSecurityGroupId
                - !Ref AWS::NoValue
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              sudo sh -c 'echo "***** Welcome to Bastion Host *****" > /etc/motd'
      Tags:
        - Key: application
          Value: !Ref application
        - Key: cost
          Value: !Ref cost
        - Key: environment
          Value: !Ref environment
        - Key: Name
          Value: !Join
            - ''
            - - !Ref uniqueString
              - '-bastion-vm'
        - Key: group
          Value: !Ref group
        - Key: owner
          Value: !Ref owner
  bastionLaunchConfig:
    Condition: Autoscale
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: !FindInMap
        - imageRegionMap
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: !Ref instanceType
      AssociatePublicIpAddress: true
      KeyName: !Ref sshKey
      SecurityGroups:
        - !If
          - useBastionSecurityGroupId
          - !Ref bastionSecurityGroupId
          - !Ref AWS::NoValue
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash
            - |
              sudo sh -c 'echo "***** Welcome to Bastion Host *****" > /etc/motd'

  bastionAutoscaleGroup:
    Condition: Autoscale
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: !Join
            - ''
            - - !Ref uniqueString
              - '-bastion-autoscaling-group'
      Tags:
        - Key: application
          PropagateAtLaunch: true
          Value: !Ref application
        - Key: cost
          PropagateAtLaunch: true
          Value: !Ref cost
        - Key: environment
          PropagateAtLaunch: true
          Value: !Ref environment
        - Key: group
          PropagateAtLaunch: true
          Value: !Ref group
        - Key: Name
          PropagateAtLaunch: true
          Value: !Join
            - ''
            - - !Ref uniqueString
              - '-bastion-vm'
        - Key: owner
          PropagateAtLaunch: true
          Value: !Ref owner
      VPCZoneIdentifier: !Ref mgmtSubnets
      Cooldown: '600'
      HealthCheckGracePeriod: 120
      LaunchConfigurationName: !Ref bastionLaunchConfig
      MaxSize: !Ref scalingMaxSize
      MinSize: !Ref scalingMinSize
      MetricsCollection:
        - Granularity: 1Minute
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 1
        MinInstancesInService: 1
        PauseTime: PT3M
