AWSTemplateFormatVersion: '2010-09-09'
Description: This template represents an example of a linked deployment of the BIG-IP
  Standalone template
Resources:
  Access:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation-v2/v3.1.0.0/examples/modules/bigip-standalone/bigip-standalone.yaml
      Parameters:
        instanceProfile: ''
        bigIpRuntimeInitConfig: 'https://some-delivery-locatoion.com/config.yaml'
        bigIpRuntimeInitPackageUrl: 'https://cdn.f5.com/product/cloudsolutions/f5-bigip-runtime-init/v1.6.2/dist/f5-bigip-runtime-init-1.6.2-1.gz.run'
        cfeS3Bucket: ''
        cfeTag: ''
        customImageId: ami-id
        externalSelfPublicIpId: eip-000003
        externalServicePublicIpIds: 'eip-00003,eip-00004,eip-00005'
        externalSecurityGroupId: nsg-00002
        externalSelfIp: ''
        externalServiceIps: ''
        externalSubnetId: sub-00002
        imageId: ami-id
        instanceType: m5.4xlarge
        internalSecurityGroupId: nsg-00004
        internalSelfIp: ''
        internalSubnetId: sub-00003
        mgmtPublicIpId: eip-00002
        mgmtSecurityGroupId: nsg-000001
        mgmtAddress: ''
        mgmtSubnetId: sub-00001
        numSecondaryPrivateIpAddress: 2
        sshKey: example-ssh-key-name
        uniqueString: myuniqstr
Outputs:
  stackName:
    Value: !GetAtt 'BigIp.Outputs.stackName'
  bigIpInstanceId:
    Value: !GetAtt 'BigIp.Outputs.bigIpInstanceId'
  bigIp2nicExternalInterfacePrivateIp:
    Value: !GetAtt 'BigIp.Outputs.bigIp2nicExternalInterfacePrivateIp'
  bigIp3NicExternalInterfacePrivateIp:
    Value: !GetAtt 'BigIp.Outputs.bigIp3NicExternalInterfacePrivateIp'
  bigIp3NicInternalInterfacePrivateIp:
    Value: !GetAtt 'BigIp.Outputs.bigIp3NicInternalInterfacePrivateIp'
