AWSTemplateFormatVersion: 2010-09-09
Description: >-
  BIG-IP Autoscale Template is intended to deploy Autoscale Group of BIG-IP
  virtual editions
Conditions:
  isBigIqLicensing: !Equals
    - bigiq
    - !Ref licenseType
  externalTargetGroupHttpProvided: !Not
    - !Equals
      - ''
      - !Ref externalTargetGroupHttp
  externalTargetGroupHttpsProvided: !Not
    - !Equals
      - ''
      - !Ref externalTargetGroupHttps
  internalTargetGroupHttpsProvided: !Not
    - !Equals
      - ''
      - !Ref internalTargetGroupHttps
  internalTargetGroupHttpProvided: !Not
    - !Equals
      - ''
      - !Ref internalTargetGroupHttp
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: BIG-IP Configuration
        Parameters:
          - bigIpRuntimeInitConfig
          - bigIpRuntimeInitPackageUrl
      - Label:
          default: Autoscale Group
        Parameters:
          - scalingMinSize
          - scalingMaxSize
          - scaleDownBytesThreshold
          - scaleUpBytesThreshold
          - lowCpuThreshold
          - highCpuThreshold
          - metricNameSpace
      - Label:
          default: Networking
        Parameters:
          - subnets
          - internalTargetGroupHttps
          - internalTargetGroupHttp
          - externalTargetGroupHttp
          - externalTargetGroupHttps
          - bigIpExternalSecurityGroup
      - Label:
          default: EC2 Instances
        Parameters:
          - imageId
          - instanceType
          - provisionPublicIp
          - sshKey
          - bigIpInstanceProfile
          - licenseType
      - Label:
          default: Tags
        Parameters:
          - cost
          - environment
          - group
          - owner
      - Label:
          default: Notifications
        Parameters:
          - notificationEmail
          - snsEvents
          - bigIqLicenseRevokeSnsTopic
          - bigIqNotificationRole
    ParameterLabels:
      application:
        default: Application
      bigIpExternalSecurityGroup:
        default: BIG-IP external security group
      bigIpInstanceProfile:
        default: BIG-IP instance profile with applied IAM policy
      bigIpRuntimeInitPackageUrl:
        default: Runtime Init Package
      bigIqLicenseRevokeSnsTopic:
        default: Provides SNS Topic ARN used for triggering Lambda Function for revoking license on BIG-IQ
      bigIqNotificationRole:
        default: The ARN of the IAM role to assign to the Lifecycle Hook
      cost:
        default: Cost Center
      environment:
        default: Environment
      externalTargetGroupHttp:
        default: External Load Balancer Targert Group with BIG-IP VEs for HTTP requests.
      externalTargetGroupHttps:
        default: External Load Balancer Targert Group with BIG-IP VEs for HTTPS requests
      group:
        default: Group
      highCpuThreshold:
        default: High CPU Percentage threshold to begin scaling up BIG-IP VE instances.
      imageId:
        default: Image Id
      instanceType:
        default: Enter valid instance type.
      internalTargetGroupHttp:
        default: Internal Load Balancer Target Group with BIG-IP VEs. for HTTP requests
      internalTargetGroupHttps:
        default: Internal Load Balancer Target Group with BIG-IP VEs. for HTTPS requests
      licenseType:
        default: Specifies licence type used for BIG-IP VE.
      lowCpuThreshold:
        default: Low CPU Percentage threshold to begin scaling down BIG-IP VE instances.
      metricNameSpace:
        default: CloudWatch custom metric name space
      notificationEmail:
        default: Notification Email
      owner:
        default: Owner
      provisionPublicIp:
        default: Provision Public IP addresses for the BIG-IP interfaces
      scaleDownBytesThreshold:
        default: Incoming bytes threshold to begin scaling down BIG-IP VE instances.
      scaleUpBytesThreshold:
        default: Incoming bytes threshold to begin scaling up BIG-IP VE instances.
      scalingMaxSize:
        default: Maximum number of BIG-IP instances (2-8) that can be created in the Autoscale Group
      scalingMinSize:
        default: Minimum number of BIG-IP instances (2-8) that can be created in the Autoscale Group
      snsEvents:
        default: Provides list of SNS Events used for sending Notifications on Autoscale group
      sshKey:
        default: Supply the public key that will be used for SSH authentication to the BIG-IP and application virtual machines.
      subnets:
        default: Public or external subnets for the availability zones
  Version: 1.0.0
Outputs:
  stackName:
    Description: bigip-autoscale nested stack name
    Value: !Ref "AWS::StackName"
  bigIpAutoscaleGroup:
    Description: BIG-IP Autoscale Group
    Value: !Ref BigipAutoscaleGroup
  snsTopic:
    Description: SNS topic Autoscale should notify
    Value: !Ref SNSTopic
Parameters:
  application:
    Default: f5app
    Description: Application Tag.
    Type: String
  bigIpExternalSecurityGroup:
    Description: REQUIRED - BIG-IP external security group.
    Type: String
  bigIpInstanceProfile:
    Description: REQUIRED - BIG-IP instance profile with applied IAM policy.
    Type: String
  bigIpRuntimeInitConfig:
    Description: 'REQUIRED - Supply a URL to the bigip-runtime-init configuration file in YAML or JSON format, or an escaped JSON string to use for f5-bigip-runtime-init configuration.'
    Type: String
  bigIpRuntimeInitPackageUrl:
    Default: 'https://cdn.f5.com/product/cloudsolutions/f5-bigip-runtime-init/v1.2.0/dist/f5-bigip-runtime-init-1.2.0-1.gz.run'
    Description: URL for BIG-IP Runtime Init package.
    Type: String
  bigIqLicenseRevokeSnsTopic:
    Default: ''
    Description: Provides SNS Topic ARN used for triggering Lambda Function for revoking license on BIG-IQ.
    Type: String
  bigIqNotificationRole:
    Default: ''
    Description: The ARN of the IAM role to assign to the Lifecycle Hook.
    Type: String
  cost:
    Default: f5cost
    Description: Cost Center Tag.
    Type: String
  environment:
    Default: f5env
    Description: Environment Tag.
    Type: String
  externalTargetGroupHttp:
    Default: ''
    Description: External Load Balancer Targert Group with BIG-IP VEs for HTTP requests.
    Type: String
  externalTargetGroupHttps:
    Default: ''
    Description: External Load Balancer Targert Group with BIG-IP VEs for HTTPS requests.
    Type: String
  group:
    Default: f5group
    Description: Group Tag.
    Type: String
  highCpuThreshold:
    ConstraintDescription: Select a value between 0 to 100
    Default: 80
    Description: High CPU Percentage threshold to begin scaling up BIG-IP VE instances.
    MaxValue: 100
    MinValue: 0
    Type: Number
  imageId:
    Description: REQUIRED - Provide BIG-IP AMI ID you wish to deploy.
    MaxLength: 255
    MinLength: 1
    Type: String
  instanceType:
    AllowedValues:
      - m3.2xlarge
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - cc2.8xlarge
      - c5n.2xlarge
      - c5n.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type for BIG-IP
    Default: m5.2xlarge
    Description: Enter valid instance type.
    Type: String
  internalTargetGroupHttp:
    Default: ''
    Description: Internal Load Balancer Target Group with BIG-IP VEs.
    Type: String
  internalTargetGroupHttps:
    Default: ''
    Description: Internal Load Balancer Target Group with BIG-IP VEs.
    Type: String
  licenseType:
    AllowedValues:
      - payg
      - bigiq
    Default: payg
    Description: Specifies licence type used for BIG-IP VE.
    Type: String
  lowCpuThreshold:
    ConstraintDescription: Select a value between 0 to 100
    Default: 20
    Description: Low CPU Percentage threshold to begin scaling down BIG-IP VE instances.
    MaxValue: 100
    MinValue: 0
    Type: Number
  metricNameSpace:
    Default: f5-scaling-metrics
    Description: CloudWatch namespace used for custom metrics. This should match the namespace defined in your telemetry services declaration within bigipRuntimInitConfig.
    Type: String
  notificationEmail:
    AllowedPattern: .+@.+
    ConstraintDescription: Must be a valid email address.
    Description: REQUIRED - Valid email address to send Auto Scaling event notifications.
    Type: String
  owner:
    Default: f5owner
    Description: Owner Tag.
    Type: String
  provisionPublicIp:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Whether or not to provision Public IP Addresses for the BIG-IP Network Interfaces. By Default no Public IP addresses are provisioned.
    Type: String
  scaleDownBytesThreshold:
    Default: 10000000
    Description: Incoming bytes threshold to begin scaling down BIG-IP VE instances.
    Type: Number
  scaleUpBytesThreshold:
    Default: 20000000
    Description: Incoming bytes threshold to begin scaling up BIG-IP VE instances.
    Type: Number
  scalingMaxSize:
    ConstraintDescription: Must be a number between 2-100
    Default: 2
    Description: Maximum number of BIG-IP instances (2-100) that can be created in the Auto Scale Group.
    MaxValue: 100
    MinValue: 2
    Type: Number
  scalingMinSize:
    ConstraintDescription: Must be a number between 1-99
    Default: 1
    Description: Minimum number of BIG-IP instances (1-99) you want available in the Auto Scale Group.
    MaxValue: 99
    MinValue: 1
    Type: Number
  snsEvents:
    Default: autoscaling:EC2_INSTANCE_LAUNCH,autoscaling:EC2_INSTANCE_LAUNCH_ERROR
    Description: Provides list of SNS Topics used on Autoscale Group.
    Type: List<String>
  sshKey:
    Description: REQUIRED - Supply the public key that will be used for SSH authentication to the BIG-IP and application virtual machines.
    Type: AWS::EC2::KeyPair::KeyName
  subnets:
    ConstraintDescription: The subnet IDs must be within an existing VPC
    Description: REQUIRED - Public or external subnets for the availability zones.
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  SNSTopic:
    Properties:
      Subscription:
        - Endpoint: !Ref notificationEmail
          Protocol: email
    Type: 'AWS::SNS::Topic'
  LifecycleHook:
    Condition: isBigIqLicensing
    Properties:
      AutoScalingGroupName: !Ref BigipAutoscaleGroup
      HeartbeatTimeout: 120
      LifecycleTransition: autoscaling:EC2_INSTANCE_TERMINATING
      NotificationTargetARN: !Ref bigIqLicenseRevokeSnsTopic
      RoleARN: !Ref bigIqNotificationRole
    Type: 'AWS::AutoScaling::LifecycleHook'
  BigipAutoscaleGroup:
    CreationPolicy:
      ResourceSignal:
        Count: !Ref scalingMinSize
        Timeout: PT30M
    Properties:
      Cooldown: '1500'
      DesiredCapacity: !Ref scalingMinSize
      HealthCheckGracePeriod: 1500
      HealthCheckType: EC2
      LaunchConfigurationName: !Ref BigipLaunchConfig
      TargetGroupARNs:
        - !If
          - externalTargetGroupHttpProvided
          - !Ref externalTargetGroupHttp
          - !Ref 'AWS::NoValue'
        - !If
          - externalTargetGroupHttpsProvided
          - !Ref externalTargetGroupHttps
          - !Ref 'AWS::NoValue'
        - !If
          - internalTargetGroupHttpProvided
          - !Ref internalTargetGroupHttp
          - !Ref 'AWS::NoValue'
        - !If
          - internalTargetGroupHttpsProvided
          - !Ref internalTargetGroupHttps
          - !Ref 'AWS::NoValue'
      MaxSize: !Ref scalingMaxSize
      MetricsCollection:
        - Granularity: 1Minute
      MinSize: !Ref scalingMinSize
      NotificationConfigurations:
        - NotificationTypes: !Ref snsEvents
          TopicARN: !Ref SNSTopic
        - !If
          - isBigIqLicensing
          - NotificationTypes:
              - 'autoscaling:EC2_INSTANCE_TERMINATE'
            TopicARN: !Ref bigIqLicenseRevokeSnsTopic
          - !Ref 'AWS::NoValue'
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: !Join
            - ''
            - - 'BIG-IP Autoscale Instance: '
              - !Ref 'AWS::StackName'
        - Key: Application
          PropagateAtLaunch: true
          Value: !Ref application
        - Key: cost
          PropagateAtLaunch: true
          Value: !Ref cost
        - Key: Environment
          PropagateAtLaunch: true
          Value: !Ref environment
        - Key: Group
          PropagateAtLaunch: true
          Value: !Ref group
        - Key: Owner
          PropagateAtLaunch: true
          Value: !Ref owner
      VPCZoneIdentifier: !Ref subnets
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MaxBatchSize: 5
        MinInstancesInService: 1
        PauseTime: PT8M
  BigipHighCpuAlarm:
    DependsOn: BigipAutoscaleGroup
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref BigipScaleUpPolicy
      AlarmDescription: >-
        CPU usage percentage exceeds average threshold after 1 successive
        interval of 1 minute
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: F5_system_cpu
      Namespace: !Ref metricNameSpace
      Period: 60
      Statistic: Average
      Threshold: !Ref highCpuThreshold
    Type: 'AWS::CloudWatch::Alarm'
  BigipHighbytesAlarm:
    DependsOn: BigipAutoscaleGroup
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref BigipScaleUpPolicy
      AlarmDescription: >-
        Throughput exceeds average threshold after 1 successive interval of 1
        minute
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: F5_throughputIn_sys/performance/throughput/In_Current
      Namespace: !Ref metricNameSpace
      Period: 60
      Statistic: Average
      Threshold: !Ref scaleUpBytesThreshold
    Type: 'AWS::CloudWatch::Alarm'
  BigipLaunchConfig:
    Properties:
      AssociatePublicIpAddress: !Ref provisionPublicIp
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeType: gp2
        - DeviceName: /dev/xvdb
          NoDevice: true
      IamInstanceProfile: !Ref bigIpInstanceProfile
      ImageId: !Ref imageId
      InstanceMonitoring: false
      InstanceType: !Ref instanceType
      KeyName: !Ref sshKey
      SecurityGroups:
        - !Ref bigIpExternalSecurityGroup
      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -x
            - |+

            - |
              # Log to local file and serial console
            - |
              mkdir -p /var/log/cloud /config/cloud /var/config/rest/downloads
            - |
              LOG_FILE=/var/log/cloud/startup-script.log
            - |
              echo 'Initializing Runtime Init.'
            - |
              npipe=/tmp/$$.tmp
            - |
              trap "rm -f $npipe" EXIT
            - |
              mknod $npipe p
            - |
              tee <$npipe -a ${LOG_FILE} /dev/ttyS0 &
            - |
              exec 1>&-
            - |
              exec 1>$npipe
            - |
              exec 2>&1
            - |+

            - |
              echo "$(date +"%Y-%m-%dT%H:%M:%S.%3NZ") : Startup Script Start"
            - >
              # Optional optimizations required as early as possible in boot
              sequence before MCDP starts up.
            - |
              /usr/bin/setdb provision.extramb 1000
            - |
              /usr/bin/setdb restjavad.useextramb true
            - >
              ! grep -q 'provision asm' /config/bigip_base.conf && echo 'sys
              provision asm { level nominal }' >> /config/bigip_base.conf
            - |+

            - |
              # VARS FROM TEMPLATE
            - >
            - PACKAGE_URL='
            - !Ref bigIpRuntimeInitPackageUrl
            - |
              '
            - RUNTIME_CONFIG='
            - !Ref bigIpRuntimeInitConfig
            - |
              '
            - |
              # Download or render f5-bigip-runtime-init config
            - |
              if [[ "${RUNTIME_CONFIG}" =~ ^http.* ]]; then
            - |2
                   for i in {1..30}; do
            - |2
                      curl -sfv --retry 1 --connect-timeout 5 -L "${RUNTIME_CONFIG}" -o /config/cloud/runtime-init.conf && break || sleep 10
            - |2
                   done
            - |
              else
            - |2
                 printf '%s\n' "${RUNTIME_CONFIG}" | jq .  > /config/cloud/runtime-init.conf
            - |
              fi
            - |+

            - |
              # Download and install f5-bigip-runtime-init package
            - |
              for i in {1..30}; do
            - |2
                 curl -fv --retry 1 --connect-timeout 5 -L "${PACKAGE_URL}" -o "/var/config/rest/downloads/${PACKAGE_URL##*/}" && break || sleep 10
            - |
              done
            - |+

            - |
              # Run
            - |
              bash "/var/config/rest/downloads/${PACKAGE_URL##*/}" -- '--cloud aws'
            - |+

            - |
              # Execute Runtime-init
            - |
              f5-bigip-runtime-init --config-file /config/cloud/runtime-init.conf
            - |+

            - '[[ $? -eq 0 ]] && /opt/aws/bin/cfn-signal -e 0 --stack '
            - !Ref 'AWS::StackName'
            - ' --resource BigipAutoscaleGroup --region '
            - !Ref 'AWS::Region'
            - |+

            - |+

            - |
              echo "$(date +"%Y-%m-%dT%H:%M:%S.%3NZ") : Startup Script Finish"
            - |+

    Type: 'AWS::AutoScaling::LaunchConfiguration'
  BigipLowCpuAlarm:
    DependsOn: BigipAutoscaleGroup
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref BigipScaleDownPolicy
      AlarmDescription: >-
        CPU usage percentage below average threshold after 10 datapoints over 10 minutes
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 10
      MetricName: F5_system_cpu
      Namespace: !Ref metricNameSpace
      Period: 60
      Statistic: Average
      Threshold: !Ref lowCpuThreshold
    Type: 'AWS::CloudWatch::Alarm'
  BigipLowbytesAlarm:
    DependsOn: BigipAutoscaleGroup
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref BigipScaleDownPolicy
      AlarmDescription: >-
        Throughput below average threshold for after 10 datapoints over 10 minutes
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 10
      MetricName: F5_throughputIn_sys/performance/throughput/In_Current
      Namespace: !Ref metricNameSpace
      Period: 60
      Statistic: Average
      Threshold: !Ref scaleDownBytesThreshold
    Type: 'AWS::CloudWatch::Alarm'
  BigipScaleDownPolicy:
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref BigipAutoscaleGroup
      Cooldown: '1500'
      ScalingAdjustment: -1
    Type: 'AWS::AutoScaling::ScalingPolicy'
  BigipScaleUpPolicy:
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref BigipAutoscaleGroup
      Cooldown: '1500'
      ScalingAdjustment: 1
    Type: 'AWS::AutoScaling::ScalingPolicy'
