AWSTemplateFormatVersion: '2010-09-09'
Description: This template represents an example of a linked deployment of the BIG-IP
  Autoscale template
Resources:
  Access:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        https://raw.githubusercontent.com/F5Networks/f5-aws-cloudformation-v2/v3.1.0.0/examples/modules/bigip-autoscale/bigip-autoscale.yaml
      Parameters:
        bigIpExternalSecurityGroup: example-security-group
        instanceProfile: example-instance-profile
        bigIpRuntimeInitConfig: https://some-delivery-locatoion.com/config.yaml
        bigIpRuntimeInitPackageUrl: https://cdn.f5.com/product/cloudsolutions/f5-bigip-runtime-init/v1.6.2/dist/f5-bigip-runtime-init-1.6.2-1.gz.run
        bigIqLicenseRevokeSnsTopic: ''
        bigIqNotificationRole: ''
        externalTargetGroupHttp: example-target-group-http
        externalTargetGroupHttps: example-target-group-https
        scaleOutCpuThreshold: 0
        imageId: ami-id
        instanceType: m5.4xlarge
        internalTargetGroupHttp: ''
        internalTargetGroupHttps: ''
        licenseType: payg
        maxBatchSize: 5
        metricNameSpace: bigip-throughput
        minInstancesInService: 1
        notificationEmail: example@mail.com
        pauseTime: 480
        provisionPublicIp: 'true'
        scaleInThroughputThreshold: 10000
        scaleOutThroughputThreshold: 35000
        scalingMaxSize: 3
        scalingMinSize: 1
        snsEvents: autoscaling:EC2_INSTANCE_LAUNCH,autoscaling:EC2_INSTANCE_LAUNCH_ERROR
        sshKey: example-ssh-key-name
        subnets:
          - subnet-000001
          - subnet-000002
          - subnet-000003
Outputs:
  stackName:
    Value: !GetAtt 'BigIp.Outputs.stackName'
  bigIpAutoscaleGroup:
    Value: !GetAtt 'BigIp.Outputs.bigIpAutoscaleGroup'
  snsTopic:
    Value: !GetAtt 'BigIp.Outputs.snsTopic'
